START_DATE = "2005-01-01"
END_DATE = "2024-12-31"
REBALANCE_FREQ = "M"

ACTIVE_CANDIDATE_SIZE = 100
ACTIVE_PORTFOLIO_SIZE = 50
MAX_STOCK_WEIGHT = 0.05
SECTOR_CAPACITY = .08

ETF_UNIVERSE = ["EFA", "EEM", "TLT", "LQD", "GLD", "DBC", "VNQ"]
MARKET_BENCHMARK = "VTI"